"""empty message

Revision ID: 1658bdd37b17
Revises: ff8aed8fa5b3
Create Date: 2020-10-20 19:36:49.072582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1658bdd37b17'
down_revision = 'ff8aed8fa5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('structureprice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('structureprice', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
