"""empty message

Revision ID: 25369b324ece
Revises: e76f76feed0d
Create Date: 2020-10-13 17:45:09.104690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25369b324ece'
down_revision = 'e76f76feed0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoesmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_shoesmodel_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoesmodel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shoesmodel_name'), type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
