"""empty message

Revision ID: 770640f04f4d
Revises: ceff154a032f
Create Date: 2020-09-23 22:32:45.910373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770640f04f4d'
down_revision = 'ceff154a032f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('seller', sa.String(length=30), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('search_query', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shoes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoes')
    # ### end Alembic commands ###
