"""empty message

Revision ID: 773bbd69c276
Revises: 25369b324ece
Create Date: 2020-10-19 00:12:59.564821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773bbd69c276'
down_revision = '25369b324ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoesmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subname', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_shoesmodel_subname'), ['subname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoesmodel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shoesmodel_subname'), type_='unique')
        batch_op.drop_column('subname')

    # ### end Alembic commands ###
