"""empty message

Revision ID: 94d8aaae3fee
Revises: 770640f04f4d
Create Date: 2020-09-27 14:47:30.007309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d8aaae3fee'
down_revision = '770640f04f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
