"""empty message

Revision ID: e76f76feed0d
Revises: 459849e1abd4
Create Date: 2020-10-13 16:51:05.984463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76f76feed0d'
down_revision = '459849e1abd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoesmodel_hashtag',
    sa.Column('shoesmodel_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], name=op.f('fk_shoesmodel_hashtag_hashtag_id_hashtag'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shoesmodel_id'], ['shoesmodel.id'], name=op.f('fk_shoesmodel_hashtag_shoesmodel_id_shoesmodel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shoesmodel_id', 'hashtag_id', name=op.f('pk_shoesmodel_hashtag'))
    )
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shoesmodel_id', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shoes_shoesmodel_id_shoesmodel'), 'shoesmodel', ['shoesmodel_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shoes_shoesmodel_id_shoesmodel'), type_='foreignkey')
        batch_op.drop_column('shoesmodel_id')

    op.drop_table('shoesmodel_hashtag')
    # ### end Alembic commands ###
